# Generated by Django 5.0.4 on 2024-04-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coresubject',
            name='test',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='test',
        ),
    ]
