# Generated by Django 5.0.4 on 2024-04-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_coresubject_test_remove_ticket_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='day_of_post',
            field=models.DateField(default=50.6, verbose_name='Day of Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_of_post',
            field=models.TimeField(verbose_name='Time of Post'),
        ),
    ]
